"""add is_active to product variant

Revision ID: 24d2df87d43b
Revises: a0f8ac3f481c
Create Date: 2026-02-20 04:29:42.676995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24d2df87d43b'
down_revision: Union[str, Sequence[str], None] = 'a0f8ac3f481c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productvariant', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_productvariant_is_active'), 'productvariant', ['is_active'], unique=False)
    op.execute("UPDATE productvariant SET is_active = TRUE")
    op.alter_column('productvariant', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productvariant_is_active'), table_name='productvariant')
    op.drop_column('productvariant', 'is_active')
    # ### end Alembic commands ###
