"""remove color-size table, add option name-value 1-2

Revision ID: a0f8ac3f481c
Revises: afc67d9f530b
Create Date: 2026-02-18 12:31:57.021954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a0f8ac3f481c'
down_revision: Union[str, Sequence[str], None] = 'afc67d9f530b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productvariant', sa.Column('option1_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('productvariant', sa.Column('option1_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('productvariant', sa.Column('option2_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('productvariant', sa.Column('option2_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_productvariant_color'), table_name='productvariant')
    op.drop_index(op.f('ix_productvariant_size'), table_name='productvariant')
    op.create_index(op.f('ix_productvariant_option1_name'), 'productvariant', ['option1_name'], unique=False)
    op.create_index(op.f('ix_productvariant_option1_value'), 'productvariant', ['option1_value'], unique=False)
    op.create_index(op.f('ix_productvariant_option2_name'), 'productvariant', ['option2_name'], unique=False)
    op.create_index(op.f('ix_productvariant_option2_value'), 'productvariant', ['option2_value'], unique=False)
    op.drop_column('productvariant', 'size')
    op.drop_column('productvariant', 'color')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productvariant', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('productvariant', sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_productvariant_option2_value'), table_name='productvariant')
    op.drop_index(op.f('ix_productvariant_option2_name'), table_name='productvariant')
    op.drop_index(op.f('ix_productvariant_option1_value'), table_name='productvariant')
    op.drop_index(op.f('ix_productvariant_option1_name'), table_name='productvariant')
    op.create_index(op.f('ix_productvariant_size'), 'productvariant', ['size'], unique=False)
    op.create_index(op.f('ix_productvariant_color'), 'productvariant', ['color'], unique=False)
    op.drop_column('productvariant', 'option2_value')
    op.drop_column('productvariant', 'option2_name')
    op.drop_column('productvariant', 'option1_value')
    op.drop_column('productvariant', 'option1_name')
    # ### end Alembic commands ###
