"""add product variant

Revision ID: afc67d9f530b
Revises: 84b8cc80aa5f
Create Date: 2026-02-15 13:40:19.004989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'afc67d9f530b'
down_revision: Union[str, Sequence[str], None] = '84b8cc80aa5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1️⃣ Create productvariant table
    op.create_table(
        'productvariant',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('size', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('stock', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['product.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_productvariant_color'), 'productvariant', ['color'])
    op.create_index(op.f('ix_productvariant_size'), 'productvariant', ['size'])

    # 2️⃣ Add product_variant_id as NULLABLE first
    op.add_column(
        'orderitem',
        sa.Column('product_variant_id', sa.Integer(), nullable=True)
    )

    # 3️⃣ Create default variant for each product
    op.execute("""
        INSERT INTO productvariant (product_id, color, size, price, stock)
        SELECT id, NULL, NULL, price, 0 FROM product
    """)

    # 4️⃣ Update orderitem to link to created variant
    op.execute("""
        UPDATE orderitem oi
        SET product_variant_id = pv.id
        FROM productvariant pv
        WHERE oi.product_id = pv.product_id
    """)

    # 5️⃣ Make column NOT NULL
    op.alter_column('orderitem', 'product_variant_id', nullable=False)

    # 6️⃣ Add foreign key
    op.create_foreign_key(
        'orderitem_product_variant_id_fkey',
        'orderitem',
        'productvariant',
        ['product_variant_id'],
        ['id']
    )

    # 7️⃣ Now safe to remove old columns
    op.drop_constraint(op.f('orderitem_product_id_fkey'), 'orderitem', type_='foreignkey')
    op.drop_column('orderitem', 'product_id')
    op.drop_column('product', 'price')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orderitem', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.create_foreign_key(op.f('orderitem_product_id_fkey'), 'orderitem', 'product', ['product_id'], ['id'])
    op.drop_column('orderitem', 'product_variant_id')
    op.drop_index(op.f('ix_productvariant_size'), table_name='productvariant')
    op.drop_index(op.f('ix_productvariant_color'), table_name='productvariant')
    op.drop_table('productvariant')
    # ### end Alembic commands ###
