"""change to have stripe session, float to int, and products relation

Revision ID: b667c4998a4e
Revises: 830aaa13a2ff
Create Date: 2026-01-10 15:37:03.133553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b667c4998a4e'
down_revision: Union[str, Sequence[str], None] = '830aaa13a2ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('total_price_baths', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_order_stripe_session_id'), 'order', ['stripe_session_id'], unique=True)
    op.drop_column('order', 'total_price')
    op.add_column('orderitem', sa.Column('price_at_purchase_baths', sa.Integer(), nullable=False))
    op.drop_column('orderitem', 'price_at_purchase')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitem', sa.Column('price_at_purchase', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('orderitem', 'price_at_purchase_baths')
    op.add_column('order', sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_order_stripe_session_id'), table_name='order')
    op.drop_column('order', 'total_price_baths')
    # ### end Alembic commands ###
